TASK_TYPE = {
    # "PCBA": "classification",
    "muv": "classification",
    "hiv": "classification",
    "bace": "classification",
    "bbbp": "classification",
    "tox21": "classification",
    "toxcast": "classification",
    "sider": "classification",
    "clintox": "classification",
    # "QM7": "regression",
    # "QM7b": "regression",
    # "QM8": "regression",
    # "QM9": "regression",
    "esol": "regression",
    "freesolv": "regression",
    "lipo": "regression",
    # "PDBbind": "regression",
}


CLASSIFICATION = {
    "PCBA": {
        "category": "Biophysics",
        "task": "Classification",
        "num_tasks": 128,
        "num_data": 437929,
        "split": "Random",
        "metric": "PRC-AUC",
        "conformer": False,
    },
    "muv": {
        "category": "Biophysics",
        "task": "Classification",
        "num_tasks": 17,
        "num_data": 93087,
        "split": "Random",
        "metric": "PRC-AUC",
        "conformer": False,
    },
    "hiv": {
        "category": "Biophysics",
        "task": "Classification",
        "num_tasks": 1,
        "num_data": 41127,
        "split": "Scaffold",
        "metric": "ROC-AUC",
        "conformer": False,
    },
    "bace": {
        "category": "Biophysics",
        "task": "Classification",
        "num_tasks": 1,
        "num_data": 1513,
        "split": "Scaffold",
        "metric": "ROC-AUC",
        "conformer": False,
    },
    "bbbp": {
        "category": "Physiology",
        "task": "Classification",
        "num_tasks": 1,
        "num_data": 2039,
        "split": "Scaffold",
        "metric": "ROC-AUC",
        "conformer": False,
    },
    "tox21": {
        "category": "Physiology",
        "task": "Classification",
        "num_tasks": 12,
        "num_data": 7831,
        "split": "Random",
        "metric": "ROC-AUC",
        "conformer": False,
    },
    "toxcast": {
        "category": "Physiology",
        "task": "Classification",
        "num_tasks": 617,
        "num_data": 8577,  # real: 8575, but IDK WTH!!
        "split": "Random",
        "metric": "ROC-AUC",
        "conformer": False,
    },
    "sider": {
        "category": "Physiology",
        "task": "Classification",
        "num_tasks": 27,
        "num_data": 1427,
        "split": "Random",
        "metric": "ROC-AUC",
        "conformer": False,
    },
    "clintox": {
        "category": "Physiology",
        "task": "Classification",
        "num_tasks": 2,
        "num_data": 1478,
        "split": "Random",
        "metric": "ROC-AUC",
        "conformer": False,
    },
}

REGRESSION = {
    "QM7": {
        "category": "Quantum Mechanics",
        "task": "Regression",
        "num_tasks": 1,
        "num_data": 7160,
        "split": "Stratified",
        "metric": "MAE",
        "conformer": True,
    },
    "QM7b": {
        "category": "Quantum Mechanics",
        "task": "Regression",
        "num_tasks": 14,
        "num_data": 7210,
        "split": "Random",
        "metric": "MAE",
        "conformer": True,
    },
    "QM8": {
        "category": "Quantum Mechanics",
        "task": "Regression",
        "num_tasks": 12,
        "num_data": 21786,
        "split": "Random",
        "metric": "MAE",
        "conformer": True,
    },
    "QM9": {
        "category": "Quantum Mechanics",
        "task": "Regression",
        "num_tasks": 12,
        "num_data": 133885,
        "split": "Random",
        "metric": "MAE",
        "conformer": True,
    },
    "esol": {
        "category": "Physical Chemistry",
        "task": "Regression",
        "num_tasks": 1,
        "num_data": 1128,
        "split": "Random",
        "metric": "RMSE",
        "conformer": False,
    },
    "freesolv": {
        "category": "Physical Chemistry",
        "task": "Regression",
        "num_tasks": 1,
        "num_data": 642,
        "split": "Random",
        "metric": "RMSE",
        "conformer": False,
    },
    "lipo": {
        "category": "Physical Chemistry",
        "task": "Regression",
        "num_tasks": 1,
        "num_data": 4200,
        "split": "Random",
        "metric": "RMSE",
        "conformer": False,
    },
    "PDBbind": {
        "category": "Biophysics",
        "task": "Regression",
        "num_tasks": 1,
        "num_data": 11908,
        "split": "Time",
        "metric": "RMSE",
        "conformer": True,
    },
}

METHOD = {
    dn: CLASSIFICATION[dn]["split"] if TASK_TYPE[dn] == "classification" else REGRESSION[dn]["split"]
    for dn in TASK_TYPE.keys()
}
